[project]
name = "bluestar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "huggingface>=0.0.1",
    "langchain>=0.3.25",
    "langgraph>=0.4.8",
    "mypy>=1.16.0",
    "python-dotenv>=1.1.0",
]
